const vk = @import("vulkan");
const builtin = @import("builtin");

pub const BaseDispatch = vk.BaseWrapper(&.{
    .createInstance,
});

pub const InstanceDispatch = vk.InstanceWrapper(&.{
    .destroyInstance,
    .createDebugUtilsMessengerEXT,
    .destroyDebugUtilsMessengerEXT,
    .createDevice,
    switch (builtin.target.os.tag) {
        .macos => .createMetalSurfaceEXT,
        .linux => .createXcbSurfaceKHR,
        else => unreachable,
    },
    .destroySurfaceKHR,
    .enumeratePhysicalDevices,
    .getPhysicalDeviceProperties,
    .getPhysicalDeviceMemoryProperties,
    .getPhysicalDeviceFeatures,
    .enumerateDeviceExtensionProperties,
    .getPhysicalDeviceSurfaceFormatsKHR,
    .getPhysicalDeviceSurfacePresentModesKHR,
    .getPhysicalDeviceSurfaceCapabilitiesKHR,
    .getPhysicalDeviceQueueFamilyProperties,
    .getPhysicalDeviceSurfaceSupportKHR,
    .getPhysicalDeviceFormatProperties,
    .getDeviceProcAddr,
});

pub const DeviceDispatch = vk.DeviceWrapper(&.{
    .destroyDevice,
    .getDeviceQueue,
    .createSemaphore,
    .createFence,
    .createImage,
    .destroyImage,
    .getImageMemoryRequirements,
    .bindImageMemory,
    .createImageView,
    .destroyImageView,
    .destroySemaphore,
    .destroyFence,
    .getSwapchainImagesKHR,
    .createSwapchainKHR,
    .destroySwapchainKHR,
    .acquireNextImageKHR,
    .deviceWaitIdle,
    .waitForFences,
    .resetFences,
    .queueSubmit,
    .queuePresentKHR,
    .createCommandPool,
    .destroyCommandPool,
    .allocateCommandBuffers,
    .freeCommandBuffers,
    .queueWaitIdle,
    .createShaderModule,
    .destroyShaderModule,
    .createPipelineLayout,
    .destroyPipelineLayout,
    .createRenderPass,
    .destroyRenderPass,
    .createGraphicsPipelines,
    .destroyPipeline,
    .createFramebuffer,
    .destroyFramebuffer,
    .beginCommandBuffer,
    .endCommandBuffer,
    .allocateMemory,
    .freeMemory,
    .createBuffer,
    .destroyBuffer,
    .getBufferMemoryRequirements,
    .mapMemory,
    .unmapMemory,
    .bindBufferMemory,
    .cmdBeginRenderPass,
    .cmdEndRenderPass,
    .cmdBindPipeline,
    .cmdDraw,
    .cmdDrawIndexed,
    .cmdSetViewport,
    .cmdPushConstants,
    .cmdSetScissor,
    .cmdBindVertexBuffers,
    .cmdBindIndexBuffer,
    .cmdCopyBuffer,
    .createDescriptorSetLayout,
    .destroyDescriptorSetLayout,
    .createDescriptorPool,
    .destroyDescriptorPool,
    .allocateDescriptorSets,
    .cmdBindDescriptorSets,
    .cmdPipelineBarrier,
    .cmdCopyBufferToImage,
    .updateDescriptorSets,
    .createSampler,
    .destroySampler,
});
